#!/bin/bash

DIR="$(dirname "$(readlink -f "$0")")"
source $DIR/../conf/cluster-admin-env.sh

if [ "$#" != "1" ];then
	echo "Usage: $0 <groupname>"
	exit 1
fi

pssh -i -h $DIR/../conf/all-hosts "sudo groupadd $1"
